import Image from "next/image";
import Link from "next/link";
import { Reveal } from "@/components/Reveal";
import { assetPath } from "@/lib/assetPath";
import { ceol } from "@/content/ceol";
import styles from "./CeoLSections.module.css";

const img = (name: string) => assetPath(`/course-${name}.jpg`);

export function CeoLSections() {
  return <main className={styles.page}>
    <section className={`section section--dark ${styles.hero}`}>
      <Image src={assetPath("/hero-training.jpg")} alt="Liderança em uma experiência do Instituto 2630" fill priority className={styles.heroImage} />
      <div className={styles.shade} />
      <div className="section__inner"><Reveal><p className="eyebrow">{ceol.hero.eyebrow}</p><h1 className="headline">{ceol.hero.headline}</h1><p className="lede">{ceol.hero.subheadline}</p><Link className="button-primary" href="#oferta">Quero viver o CEO-L <span>↗</span></Link><p className="micro">Liderança • Autoliderança • Equipe • Decisão • Planejamento • Pressão controlada</p></Reveal></div>
    </section>
    <section className="section section--light"><div className="section__inner"><Reveal><p className="eyebrow red">A pergunta que abre a consciência</p><h2 className="headline">Quem é você quando o controle desaparece?</h2><p className="lede">É fácil falar de liderança quando existe tempo, recurso, energia e previsibilidade. Mas você delega ou controla? Confia ou centraliza? Continua sendo o líder que acredita ser quando as condições deixam de ajudar?</p><p className={styles.statement}>A verdadeira liderança começa pela compreensão de si mesmo.</p></Reveal></div></section>
    <section className={`section section--dark ${styles.photoSection}`}><Image src={img("03")} alt="Equipe em uma experiência de liderança" fill className={styles.photo} /><div className={styles.shade} /><div className="section__inner"><Reveal><p className="eyebrow">O preço invisível do sucesso</p><h2 className="headline">Quanto está custando sustentar tudo?</h2><div className={styles.columns}><p>Você cresce profissionalmente, mas se afasta da família. A empresa cresce, mas tudo continua dependendo de você. Você entrega resultado, mas vive cansado e sob estresse.</p><p>Por fora, sucesso. Por dentro, pressão, controle e a sensação de carregar tudo. Você não precisa destruir sua vida pessoal para ter sucesso profissional.</p></div></Reveal></div></section>
    <section className="section section--light"><div className="section__inner"><Reveal><p className="eyebrow red">A tese</p><h2 className="headline">A pressão não cria o líder. Ela revela o líder.</h2><p className="lede">Quando conforto, previsibilidade e abundância desaparecem, padrões ficam mais visíveis. O CEO-L coloca a liderança no campo da experiência — e o debrief traduz o que aconteceu para a vida e para os negócios.</p></Reveal></div></section>
    <section className="section section--dark"><div className="section__inner"><Reveal><p className="eyebrow">O que é o CEO-L</p><h2 className="headline headline--wide">Não é uma palestra sobre liderança. É liderança sendo observada na prática.</h2><p className="lede">Uma imersão presencial de aproximadamente três dias, com turmas pequenas, missões, planejamento, comunicação, equipe, execução, adaptação, responsabilidade e debrief.</p><div className={styles.not}><span>Não é passeio militar.</span><span>Não é prova de masculinidade.</span><span>A pressão é ferramenta didática.</span></div></Reveal></div></section>
    <section className="section section--light"><div className="section__inner"><Reveal><p className="eyebrow red">Como a experiência funciona</p><h2 className="headline">Cinco fases. Uma experiência. Um líder sendo revelado.</h2></Reveal><div className={styles.phaseGrid}>{ceol.phases.map((phase, i) => <Reveal as="article" key={phase} delayMs={i * 70}><span>0{i + 1}</span><h3>{phase}</h3><p>Vivência, decisão e observação em equipe.</p></Reveal>)}</div><p className={styles.mechanism}>pressão controlada → poucos recursos → missão → equipe → decisão → debrief → aplicação</p></div></section>
    <section className={`section section--dark ${styles.photoSection}`}><Image src={img("08")} alt="Debrief e aprendizado coletivo" fill className={styles.photo} /><div className={styles.shade} /><div className="section__inner"><Reveal><p className="eyebrow">O debrief</p><h2 className="headline">Viver sem compreender é apenas experiência.</h2><p className="lede">O debrief transforma experiência em aprendizado. O que você fez? Como reagiu? Pediu ajuda? Delegou? Assumiu responsabilidade? Que padrão apareceu na sua empresa ou na sua vida?</p></Reveal></div></section>
    <section className="section section--light"><div className="section__inner"><Reveal><p className="eyebrow red">O método</p><h2 className="headline">O método deixa de ser teoria e passa a aparecer no seu comportamento.</h2></Reveal><div className={styles.pillars}>{ceol.pillars.map((pillar, i) => <div key={pillar}><span>0{i + 1}</span><strong>{pillar}</strong></div>)}</div></div></section>
    <section className="section section--dark" id="para-quem"><div className="section__inner"><Reveal><p className="eyebrow">Para quem carrega responsabilidade</p><h2 className="headline">Elevar o padrão de liderança começa por você.</h2></Reveal><div className={styles.audience}><p>Empresários, empreendedores, diretores, executivos, gestores e profissionais que precisam decidir sob pressão, construir confiança e liderar sem perder a si mesmos.</p><p className={styles.muted}>Não é para quem busca apenas curiosidade sobre o BOPE, entretenimento extremo ou uma prova física.</p></div></div></section>
    <section className={`section section--light ${styles.offer}`} id="oferta"><div className="section__inner"><Reveal><p className="eyebrow red">Uma imersão. Poucas vagas. Experiência integral.</p><h2 className="headline">Antes de liderar melhor os outros, compreenda quem está liderando.</h2><p className="lede">Datas, local, inclusões e investimento serão confirmados para cada turma.</p><Link className="button-primary" href="#contato">Quero garantir minha vaga no CEO-L <span>↗</span></Link></Reveal></div></section>
    <section className="section section--dark" id="contato"><div className="section__inner"><Reveal><p className="eyebrow">CEO-L</p><h2 className="headline">Não importa o problema, liderar é a solução.</h2><p className="lede">Lidere-se.</p><Link className="button-primary" href="mailto:contato@instituto2630.com.br">Quero viver o CEO-L <span>↗</span></Link></Reveal></div></section>
  </main>;
}
